-- stock-center 行情基础事实同步任务 seed
-- 只写入调度任务定义，不修改表结构；默认禁用，先手动验证。

INSERT INTO t_scheduler_job (
    job_code,
    job_name,
    job_type,
    description,
    parameter_schema,
    trigger_type,
    cron_expr,
    timezone,
    default_payload,
    max_instances,
    misfire_grace_seconds,
    timeout_seconds,
    retry_count,
    retry_interval_seconds,
    is_enabled,
    is_system,
    is_hidden,
    metadata
)
VALUES
(
    'sync_sector_catalog',
    '同步板块与成分股',
    'market_data',
    '每日同步 A 股概念/行业板块列表，并维护板块与股票的关联关系。',
    '{
      "sector_types":{"label":"板块类型","type":"array","default":["concept","industry"],"required":false,"description":"同步哪些板块类型。第一版支持 concept 和 industry。","options":["concept","industry"]},
      "sync_components":{"label":"同步成分股","type":"boolean","default":true,"required":false,"description":"是否同步板块与股票关联关系。"},
      "limit_sectors":{"label":"板块上限","type":"number","required":false,"description":"调试时限制每类同步多少个板块；为空表示全量。"},
      "max_concurrency":{"label":"最大并发","type":"number","default":3,"required":false,"description":"外部 provider 成分股查询并发数。","min":1,"max":10},
      "source":{"label":"数据源","type":"string","default":"akshare","required":false,"options":["akshare"],"description":"第一版板块同步使用 AkShare。"},
      "expire_missing_components":{"label":"过期缺失成分","type":"boolean","default":true,"required":false,"description":"完整同步某板块后，将本次未出现的旧成分标记 end_date。"},
      "provider_timeout_seconds":{"label":"Provider 超时秒数","type":"number","default":45,"required":false,"description":"单次外部 provider 请求超时时间，防止任务长期卡在外部网络。","min":5,"max":600}
    }'::jsonb,
    'cron',
    '20 8 * * 1-5',
    'Asia/Shanghai',
    '{"sector_types":["concept","industry"],"sync_components":true,"limit_sectors":null,"max_concurrency":3,"source":"akshare","expire_missing_components":true,"provider_timeout_seconds":45}'::jsonb,
    1,
    1800,
    7200,
    0,
    300,
    false,
    false,
    false,
    '{"source":"stock-center-bootstrap","phase":"market_data_sync"}'::jsonb
),
(
    'sync_stock_basic',
    '每周同步股票基础资料',
    'market_data',
    '每周低频同步 A 股基础资料，AkShare 为主源，MooTDX 为 fallback。',
    '{
      "source":{"label":"主数据源","type":"string","default":"akshare","required":false,"options":["akshare","mootdx"],"description":"基础资料主数据源。"},
      "include_detail":{"label":"补充详情","type":"boolean","default":true,"required":false,"description":"是否渐进补充行业、上市日期和更名信息。"},
      "detail_mode":{"label":"详情模式","type":"string","default":"missing_or_stale","required":false,"options":["missing_or_stale","missing","stale","all","none"],"description":"选择补充缺失、过期或全部详情。"},
      "max_detail_per_run":{"label":"详情补充上限","type":"number","default":300,"required":false,"description":"单次最多补充多少只股票详情。","min":0,"max":2000},
      "detail_refresh_days":{"label":"详情刷新天数","type":"number","default":90,"required":false,"description":"超过多少天视为详情过期。","min":1,"max":3650},
      "fallback_to_mootdx":{"label":"启用 fallback","type":"boolean","default":true,"required":false,"description":"AkShare 列表失败或异常时是否降级 MooTDX。"},
      "mark_delisted":{"label":"标记退市","type":"boolean","default":true,"required":false,"description":"是否根据明确退市数据更新 delisted 状态。"},
      "min_expected_count":{"label":"最小返回数量","type":"number","default":3000,"required":false,"description":"AkShare 返回数量低于该值时视为异常。","min":1,"max":10000},
      "provider_timeout_seconds":{"label":"Provider 超时秒数","type":"number","default":120,"required":false,"description":"单次外部 provider 请求超时时间，AkShare 超时后可 fallback 到 MooTDX。","min":5,"max":600}
    }'::jsonb,
    'cron',
    '30 8 * * 0',
    'Asia/Shanghai',
    '{"source":"akshare","include_detail":true,"detail_mode":"missing_or_stale","max_detail_per_run":300,"detail_refresh_days":90,"fallback_to_mootdx":true,"mark_delisted":true,"min_expected_count":3000,"provider_timeout_seconds":120}'::jsonb,
    1,
    1800,
    7200,
    0,
    300,
    false,
    false,
    false,
    '{"source":"stock-center-bootstrap","migrated_from":"stock-analysis","phase":"market_data_sync"}'::jsonb
)
ON CONFLICT (job_code) DO UPDATE SET
    job_name = EXCLUDED.job_name,
    job_type = EXCLUDED.job_type,
    description = EXCLUDED.description,
    parameter_schema = EXCLUDED.parameter_schema,
    trigger_type = EXCLUDED.trigger_type,
    cron_expr = EXCLUDED.cron_expr,
    timezone = EXCLUDED.timezone,
    default_payload = EXCLUDED.default_payload,
    max_instances = EXCLUDED.max_instances,
    misfire_grace_seconds = EXCLUDED.misfire_grace_seconds,
    timeout_seconds = EXCLUDED.timeout_seconds,
    retry_count = EXCLUDED.retry_count,
    retry_interval_seconds = EXCLUDED.retry_interval_seconds,
    is_hidden = EXCLUDED.is_hidden,
    metadata = EXCLUDED.metadata,
    updated_at = now();
