-- 全市场每日收盘数据沉淀：动态股票范围、EOD quote、分钟分区与基础因子任务。
-- 执行前请备份数据库。旧分钟事实/因子表会改名为 *_legacy，不会删除。

ALTER TABLE t_stock_pool
    ADD COLUMN IF NOT EXISTS is_dynamic BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS dynamic_rule VARCHAR(80);

COMMENT ON COLUMN t_stock_pool.is_dynamic IS '是否为动态股票池；动态池不保存实体成员关系。';
COMMENT ON COLUMN t_stock_pool.dynamic_rule IS '动态池成员规则，例如 active_a_share。';

INSERT INTO t_stock_pool (
    pool_code, pool_name, pool_type, description, is_system, is_enabled, is_dynamic, dynamic_rule, sort_order
)
VALUES (
    'all_a_share', '全市场 A 股', 'universe', '动态范围：t_stock 中所有 status=active 的 A 股，用于全市场收盘数据沉淀。',
    TRUE, TRUE, TRUE, 'active_a_share', 1
)
ON CONFLICT (pool_code) DO UPDATE SET
    description = EXCLUDED.description,
    is_system = TRUE,
    is_enabled = TRUE,
    is_dynamic = TRUE,
    dynamic_rule = 'active_a_share',
    sort_order = EXCLUDED.sort_order,
    updated_at = now();

ALTER TABLE t_quote_snapshot
    ADD COLUMN IF NOT EXISTS snapshot_kind VARCHAR(20) NOT NULL DEFAULT 'realtime';

COMMENT ON COLUMN t_quote_snapshot.snapshot_kind IS '快照类别：realtime 为盘中快照，eod 为全市场轻量收盘快照。';
CREATE INDEX IF NOT EXISTS idx_t_quote_snapshot_kind_time
    ON t_quote_snapshot(snapshot_kind, quote_time DESC);

-- 将现有非分区分钟线表保护为 legacy，然后重建为按交易日的分区主表。
DO $$
BEGIN
    IF to_regclass('public.t_minute_bar_legacy') IS NULL
       AND to_regclass('public.t_minute_bar') IS NOT NULL THEN
        ALTER TABLE t_minute_bar RENAME TO t_minute_bar_legacy;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS t_minute_bar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    stock_code VARCHAR(20) NOT NULL,
    trade_date DATE NOT NULL,
    bar_time TIMESTAMPTZ NOT NULL,
    interval VARCHAR(20) NOT NULL DEFAULT '1m',
    source VARCHAR(80) NOT NULL,
    price NUMERIC(18, 4),
    avg_price NUMERIC(18, 4),
    volume_hand BIGINT,
    volume_share BIGINT,
    amount_yuan NUMERIC(24, 2),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id, trade_date),
    CONSTRAINT uq_t_minute_bar_stock_date_time_interval_source_v2 UNIQUE (stock_code, trade_date, bar_time, interval, source)
) PARTITION BY RANGE (trade_date);

CREATE INDEX IF NOT EXISTS idx_t_minute_bar_stock_time_v2
    ON t_minute_bar(stock_code, bar_time DESC);
CREATE INDEX IF NOT EXISTS idx_t_minute_bar_trade_source
    ON t_minute_bar(trade_date DESC, source);

COMMENT ON TABLE t_minute_bar IS 'Canonical 层：按交易日分区的股票分钟线行情，收盘任务仅保留近期分区。';
COMMENT ON COLUMN t_minute_bar.id IS '分区内分钟线标识；与 trade_date 共同构成主键。';
COMMENT ON COLUMN t_minute_bar.stock_code IS '无后缀 Canonical 股票代码，关联 t_stock.stock_code。';
COMMENT ON COLUMN t_minute_bar.trade_date IS '分钟线所属 A 股交易日，按 Asia/Shanghai 计算，也是分区键。';
COMMENT ON COLUMN t_minute_bar.bar_time IS '分钟行情时间戳，带时区。';
COMMENT ON COLUMN t_minute_bar.interval IS 'K 线周期；收盘沉淀固定为 1m。';
COMMENT ON COLUMN t_minute_bar.source IS '事实来源，例如 mootdx。';
COMMENT ON COLUMN t_minute_bar.price IS '该分钟成交价或收盘价。';
COMMENT ON COLUMN t_minute_bar.avg_price IS '该分钟均价。';
COMMENT ON COLUMN t_minute_bar.volume_hand IS '该分钟成交量，单位手。';
COMMENT ON COLUMN t_minute_bar.volume_share IS '该分钟成交量，单位股。';
COMMENT ON COLUMN t_minute_bar.amount_yuan IS '该分钟成交额，单位元。';
COMMENT ON COLUMN t_minute_bar.metadata IS '非核心扩展元数据；不保存全量 provider 原始响应。';
COMMENT ON COLUMN t_minute_bar.created_at IS '入库时间。';

DO $$
DECLARE
    current_day DATE;
    next_day DATE;
BEGIN
    IF to_regclass('public.t_minute_bar_legacy') IS NOT NULL THEN
        FOR current_day IN
            EXECUTE 'SELECT DISTINCT (bar_time AT TIME ZONE ''Asia/Shanghai'')::date FROM t_minute_bar_legacy'
        LOOP
            next_day := current_day + 1;
            EXECUTE format(
                'CREATE TABLE IF NOT EXISTS t_minute_bar_p_%s PARTITION OF t_minute_bar FOR VALUES FROM (%L) TO (%L)',
                to_char(current_day, 'YYYYMMDD'), current_day, next_day
            );
        END LOOP;
        EXECUTE $migration$
            INSERT INTO t_minute_bar (
                stock_code, trade_date, bar_time, interval, source, price, avg_price,
                volume_hand, volume_share, amount_yuan, metadata, created_at
            )
            SELECT
                stock_code,
                (bar_time AT TIME ZONE 'Asia/Shanghai')::date,
                bar_time, interval, source, price, avg_price,
                volume_hand, volume_share, amount_yuan, metadata, created_at
            FROM t_minute_bar_legacy
            ON CONFLICT (stock_code, trade_date, bar_time, interval, source) DO NOTHING
        $migration$;
    END IF;
END $$;

-- 分钟因子与分钟线使用相同的保留和分区策略。
DO $$
BEGIN
    IF to_regclass('public.t_stock_factor_minute_legacy') IS NULL
       AND to_regclass('public.t_stock_factor_minute') IS NOT NULL THEN
        ALTER TABLE t_stock_factor_minute RENAME TO t_stock_factor_minute_legacy;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS t_stock_factor_minute (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    stock_code VARCHAR(20) NOT NULL,
    trade_date DATE NOT NULL,
    bar_time TIMESTAMPTZ NOT NULL,
    source VARCHAR(80) NOT NULL DEFAULT 'system:daily_close',
    vwap NUMERIC(18, 6),
    minute_return NUMERIC(18, 6),
    volume_spike_ratio NUMERIC(18, 6),
    intraday_strength NUMERIC(18, 6),
    features JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id, trade_date),
    CONSTRAINT uq_t_stock_factor_minute_business_v2 UNIQUE (stock_code, trade_date, bar_time, source)
) PARTITION BY RANGE (trade_date);

CREATE INDEX IF NOT EXISTS idx_t_stock_factor_minute_stock_time_v2
    ON t_stock_factor_minute(stock_code, bar_time DESC);

COMMENT ON TABLE t_stock_factor_minute IS 'Derived 层：按交易日分区的分钟因子，仅由 Canonical 分钟线计算。';
COMMENT ON COLUMN t_stock_factor_minute.id IS '分区内分钟因子标识；与 trade_date 共同构成主键。';
COMMENT ON COLUMN t_stock_factor_minute.stock_code IS '无后缀 Canonical 股票代码。';
COMMENT ON COLUMN t_stock_factor_minute.trade_date IS '因子所属交易日，也是分区键。';
COMMENT ON COLUMN t_stock_factor_minute.bar_time IS '对应分钟线时间戳。';
COMMENT ON COLUMN t_stock_factor_minute.source IS '因子计算来源，例如 system:daily_close。';
COMMENT ON COLUMN t_stock_factor_minute.vwap IS '截至该分钟的日内累计成交量加权均价。';
COMMENT ON COLUMN t_stock_factor_minute.minute_return IS '相对首分钟价格的累计收益率，百分比。';
COMMENT ON COLUMN t_stock_factor_minute.volume_spike_ratio IS '当前分钟成交量相对前 20 分钟均量的比值。';
COMMENT ON COLUMN t_stock_factor_minute.intraday_strength IS '日内相对首分钟价格的强度，百分比。';
COMMENT ON COLUMN t_stock_factor_minute.features IS '可重算辅助字段和缺失窗口说明。';
COMMENT ON COLUMN t_stock_factor_minute.created_at IS '入库时间。';

DO $$
DECLARE
    current_day DATE;
    next_day DATE;
BEGIN
    IF to_regclass('public.t_stock_factor_minute_legacy') IS NOT NULL THEN
        FOR current_day IN
            EXECUTE 'SELECT DISTINCT (bar_time AT TIME ZONE ''Asia/Shanghai'')::date FROM t_stock_factor_minute_legacy'
        LOOP
            next_day := current_day + 1;
            EXECUTE format(
                'CREATE TABLE IF NOT EXISTS t_stock_factor_minute_p_%s PARTITION OF t_stock_factor_minute FOR VALUES FROM (%L) TO (%L)',
                to_char(current_day, 'YYYYMMDD'), current_day, next_day
            );
        END LOOP;
        EXECUTE $migration$
            INSERT INTO t_stock_factor_minute (
                stock_code, trade_date, bar_time, source, vwap, minute_return,
                volume_spike_ratio, intraday_strength, features, created_at
            )
            SELECT
                stock_code,
                (bar_time AT TIME ZONE 'Asia/Shanghai')::date,
                bar_time, source, vwap, minute_return,
                volume_spike_ratio, intraday_strength, features, created_at
            FROM t_stock_factor_minute_legacy
            ON CONFLICT (stock_code, trade_date, bar_time, source) DO NOTHING
        $migration$;
    END IF;
END $$;

INSERT INTO t_factor_definition (
    factor_code, factor_name, factor_group, frequency, source_table, compute_method, is_rebuildable, metadata
)
VALUES
    ('ma5', '5 日均线', 'trend', 'daily', 't_daily_bar', '最近 5 个有效收盘价均值', TRUE, '{"source":"daily_market_close_ingest"}'::jsonb),
    ('ma10', '10 日均线', 'trend', 'daily', 't_daily_bar', '最近 10 个有效收盘价均值', TRUE, '{"source":"daily_market_close_ingest"}'::jsonb),
    ('ma20', '20 日均线', 'trend', 'daily', 't_daily_bar', '最近 20 个有效收盘价均值', TRUE, '{"source":"daily_market_close_ingest"}'::jsonb),
    ('return_1d', '单日收益率', 'return', 'daily', 't_daily_bar', '(close/pre_close-1)*100', TRUE, '{"source":"daily_market_close_ingest"}'::jsonb),
    ('amplitude', '日内振幅', 'volatility', 'daily', 't_daily_bar', '(high-low)/pre_close*100', TRUE, '{"source":"daily_market_close_ingest"}'::jsonb),
    ('volume_ratio', '5 日量比', 'liquidity', 'daily', 't_daily_bar', '当日成交量/前 5 日均量', TRUE, '{"source":"daily_market_close_ingest"}'::jsonb),
    ('amount_ratio', '5 日额比', 'liquidity', 'daily', 't_daily_bar', '当日成交额/前 5 日均额', TRUE, '{"source":"daily_market_close_ingest"}'::jsonb),
    ('volatility_20d', '20 日收益波动率', 'volatility', 'daily', 't_daily_bar', '最近 20 日收益率总体标准差', TRUE, '{"source":"daily_market_close_ingest"}'::jsonb),
    ('close_position', '收盘位置', 'price_action', 'daily', 't_daily_bar', '(close-low)/(high-low)', TRUE, '{"source":"daily_market_close_ingest"}'::jsonb),
    ('vwap', '日内累计 VWAP', 'microstructure', 'minute', 't_minute_bar', '累计成交额/(累计成交量*100)', TRUE, '{"source":"daily_market_close_ingest"}'::jsonb),
    ('minute_return', '分钟累计收益', 'return', 'minute', 't_minute_bar', '(当前价/首分钟价-1)*100', TRUE, '{"source":"daily_market_close_ingest"}'::jsonb),
    ('volume_spike_ratio', '分钟放量比', 'microstructure', 'minute', 't_minute_bar', '当前分钟量/前 20 分钟均量', TRUE, '{"source":"daily_market_close_ingest"}'::jsonb),
    ('intraday_strength', '盘中强度', 'microstructure', 'minute', 't_minute_bar', '当前价相对首分钟收益', TRUE, '{"source":"daily_market_close_ingest"}'::jsonb)
ON CONFLICT (factor_code) DO UPDATE SET
    factor_name = EXCLUDED.factor_name,
    factor_group = EXCLUDED.factor_group,
    frequency = EXCLUDED.frequency,
    source_table = EXCLUDED.source_table,
    compute_method = EXCLUDED.compute_method,
    is_rebuildable = EXCLUDED.is_rebuildable,
    metadata = t_factor_definition.metadata || EXCLUDED.metadata,
    updated_at = now();

INSERT INTO t_scheduler_job (
    job_code, job_name, job_type, description, parameter_schema, trigger_type, cron_expr, timezone,
    default_payload, max_instances, misfire_grace_seconds, timeout_seconds, retry_count,
    retry_interval_seconds, is_enabled, is_system, is_hidden, metadata
)
VALUES (
    'daily_market_close_ingest', '每日全市场收盘数据沉淀', 'market_data',
    '全市场收盘后沉淀日线、daily basic、分钟线、轻量 EOD quote 和基础量化因子；不运行策略或市场状态。',
    '{
      "trade_date":{"label":"交易日期","type":"string","required":false,"format":"date","description":"为空时使用当前上海交易日。"},
      "sync_daily":{"label":"同步日线","type":"boolean","default":true,"required":false,"description":"通过 Tushare 批量同步全市场日线。"},
      "sync_daily_basic":{"label":"同步日频基础指标","type":"boolean","default":true,"required":false,"description":"通过 Tushare 批量同步换手、估值和市值等日频基础指标。"},
      "sync_minute":{"label":"同步分钟线","type":"boolean","default":true,"required":false,"description":"通过 MooTDX 同步当日全市场 1 分钟线。"},
      "sync_eod_quote":{"label":"同步收盘快照","type":"boolean","default":true,"required":false,"description":"保存全市场轻量 EOD quote，不保存完整五档。"},
      "calculate_daily_factors":{"label":"计算日频因子","type":"boolean","default":true,"required":false,"description":"从 Canonical 日线计算 MA、收益、振幅、量额比和波动率。"},
      "calculate_minute_factors":{"label":"计算分钟因子","type":"boolean","default":true,"required":false,"description":"从 Canonical 分钟线计算 VWAP、收益、放量比和盘中强度。"},
      "calculate_technical_snapshot":{"label":"计算技术快照","type":"boolean","default":true,"required":false,"description":"基于 EOD quote 和已计算因子写入收盘技术快照。"},
      "minute_retention_trade_days":{"label":"分钟数据保留交易日","type":"number","default":10,"required":false,"min":1,"max":60,"description":"分钟线和分钟因子仅保留最近 N 个开市日分区。"},
      "minute_max_concurrency":{"label":"MooTDX worker 数","type":"number","default":4,"required":false,"min":1,"max":10,"description":"每个 worker 使用独立 MooTDX 连接串行拉取，避免全市场同步时共享 socket。"},
      "minute_batch_size":{"label":"分钟线批次大小","type":"number","default":200,"required":false,"min":20,"max":1000,"description":"分钟线按批次拉取并提交，降低内存峰值和单次失败影响范围。"},
      "quote_batch_size":{"label":"收盘快照批次大小","type":"number","default":200,"required":false,"min":20,"max":1000,"description":"EOD quote 按批量接口获取；批量失败时降级逐只补取。"},
      "ingest_mode":{"label":"入库模式","type":"string","default":"append_safe","required":false,"options":["append_safe","rebuild"],"description":"append_safe 跳过已有完整数据；rebuild 重算指定交易日。"}
    }'::jsonb,
    'cron', '45 15 * * 1-5', 'Asia/Shanghai',
    '{"sync_daily":true,"sync_daily_basic":true,"sync_minute":true,"sync_eod_quote":true,"calculate_daily_factors":true,"calculate_minute_factors":true,"calculate_technical_snapshot":true,"minute_retention_trade_days":10,"minute_max_concurrency":4,"minute_batch_size":200,"quote_batch_size":200,"ingest_mode":"append_safe"}'::jsonb,
    1, 3600, 21600, 1, 600, FALSE, FALSE, FALSE,
    '{"source":"daily-market-close-bootstrap","scope":"all_a_share"}'::jsonb
)
ON CONFLICT (job_code) DO UPDATE SET
    job_name = EXCLUDED.job_name,
    job_type = EXCLUDED.job_type,
    description = EXCLUDED.description,
    parameter_schema = EXCLUDED.parameter_schema,
    trigger_type = EXCLUDED.trigger_type,
    cron_expr = EXCLUDED.cron_expr,
    timezone = EXCLUDED.timezone,
    default_payload = EXCLUDED.default_payload,
    timeout_seconds = EXCLUDED.timeout_seconds,
    retry_count = EXCLUDED.retry_count,
    retry_interval_seconds = EXCLUDED.retry_interval_seconds,
    is_enabled = FALSE,
    metadata = EXCLUDED.metadata,
    updated_at = now();
