-- 20-market-partition-identity-fix.sql
-- Ensure partitioned minute tables generate id values when inserted through SQLAlchemy.
-- Safe to run repeatedly. It does not rewrite existing rows.

BEGIN;

DO $$
DECLARE
    parent_name text;
    identity_generation text;
    column_default text;
BEGIN
    FOREACH parent_name IN ARRAY ARRAY['t_minute_bar', 't_stock_factor_minute']
    LOOP
        SELECT c.identity_generation, c.column_default
        INTO identity_generation, column_default
        FROM information_schema.columns c
        WHERE c.table_schema = 'public'
          AND c.table_name = parent_name
          AND c.column_name = 'id'
        LIMIT 1;

        IF identity_generation IS NULL AND column_default IS NULL THEN
            EXECUTE format(
                'ALTER TABLE public.%I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY',
                parent_name
            );
        END IF;
    END LOOP;
END $$;

COMMENT ON COLUMN t_minute_bar.id IS '分区内分钟线标识；由 PostgreSQL identity/default 自动生成，与 trade_date 共同构成主键。';
COMMENT ON COLUMN t_stock_factor_minute.id IS '分区内分钟因子标识；由 PostgreSQL identity/default 自动生成，与 trade_date 共同构成主键。';

COMMIT;
